config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'watsons#index'
  get	'/watsons/new',	 to: 'watsons#new', as: 'new_watson'
  get '/watsons', to: 'watsons#index', as: 'watsons'
  post '/watsons',	to: 'watsons#create'
  get	'/watsons/:id', to: 'watsons#show', as: 'watson'
  get '/watsons/:id/edit', to: 'watsons#edit', as: 'edit_watson'
  patch '/watsons/:id', to: 'watsons#update'
  delete '/watsons/:id', to: 'watsons#destroy', as: 'delete_watson'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :watson
end

app/models/keyword.rb
class Keyword < ApplicationRecord
    belongs_to :watson
end

app/models/slide.rb
class Slide < ApplicationRecord
    has_many :slidewatsons
    has_many :watsons, through: :slidewatsons
end

app/models/slidewatson.rb
class Slidewatson < ApplicationRecord
    belongs_to :slide
    belongs_to :watson
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :userwatsons
    has_many :watsons, through: :userwatsons

end

app/models/userwatson.rb
class Userwatson < ApplicationRecord

    belongs_to :user
    belongs_to :watson

end

app/models/watson.rb
class Watson < ApplicationRecord
    has_many :userwatsons, dependent: :destroy
    has_many :users, through: :userwatsons
    has_many :slidewatsons, dependent: :destroy
    has_many :slides, through: :slidewatsons
    has_many :categories
    has_many :keywords
    validates :text, length: {minimum: 10}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    def self.authenticate
        key = ENV["NATURAL_LANGUAGE_UNDERSTANDING_APIKEY"]

        authenticator = Authenticators::IamAuthenticator.new(apikey: key)
        @@nlu = NaturalLanguageUnderstandingV1.new(version: "2019-12-04", authenticator: authenticator)
        @@nlu.service_url = ENV["NATURAL_LANGUAGE_UNDERSTANDING_URL"]
    end

    def self.analyze(object)
        authenticate
        
        response = @@nlu.analyze(
            text: "#{object}",
            features: {
                emotion: {}, 
                categories: {limit:3}, 
                entities: {limit:3}, 
                keywords: {limit:3}, 
                relations: {limit:3},  
                sentiment:{}
            })
          @@text_analysis = response.result
    end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end

end

app/controllers/disclaimers_controller.rb
class DisclaimersController < ActionController::Base
    def disclaimer

    end

    def start

    end

end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController 

    def index
      @slides = Slide.all
    end

    def show
      @slide = Slide.find(params[:id])

    end

end

app/controllers/watsons_controller.rb
require "ibm_watson/authenticators"
require "ibm_watson/natural_language_understanding_v1"
include IBMWatson

class WatsonsController < ApplicationController 

  def index
    @userwatsons = Userwatson.all
  end
  
  def new
    allslides = Slide.all.to_a
    @slide = allslides.sample
    @watson = Watson.new
  end

  def create
    @watson_text = params["watson"]["text"]    
    if @watson_text.empty? || @watson_text.length < 20
      redirect_to new_watson_path
    else
      ApplicationController.analyze(@watson_text)
      watson = Watson.create(
        text: @watson_text,
        sentiment_label: @@text_analysis["sentiment"]['document']['label'],
        sentiment_score: @@text_analysis["sentiment"]['document']['score'],
        emotion_sadness: @@text_analysis['emotion']['document']['emotion']['sadness'],
        emotion_joy: @@text_analysis['emotion']['document']['emotion']['joy'],
        emotion_fear: @@text_analysis['emotion']['document']['emotion']['fear'],
        emotion_disgust: @@text_analysis['emotion']['document']['emotion']['disgust'],
        emotion_anger: @@text_analysis['emotion']['document']['emotion']['anger']
      )

      keywords = @@text_analysis["keywords"]
      keywords.each do |keyword_hash|
        Keyword.create(
        text: keyword_hash["text"],
        relevance: keyword_hash["relevance"],
        count: keyword_hash["count"],
        watson_id: watson.id
      )
      end

      categories = @@text_analysis["categories"]
      categories.each do |category_hash|
        Category.create(
          score: category_hash["score"],
          label: category_hash["label"],
          watson_id: watson.id
        )
      end

      userwatson = Userwatson.create(
        user_id: current_user.id,
        watson_id: watson.id
      )
      redirect_to watson_path(watson.id)
    end
  end

  def edit
    @watson = Watson.find(params[:id])
  end

  def update
    @watson = Watson.find(params[:id])
    @sun_text = params["watson"]["text"]

    authenticator = Authenticators::IamAuthenticator.new(apikey: ENV["NATURAL_LANGUAGE_UNDERSTANDING_APIKEY"])
    natural_language_understanding = NaturalLanguageUnderstandingV1.new(
    version: "2019-07-12",
    authenticator: authenticator)

    natural_language_understanding.service_url = ENV["NATURAL_LANGUAGE_UNDERSTANDING_URL"]
    
    response = natural_language_understanding.analyze(
      text: @sun_text,
      features: {emotion: {}, categories: {limit:3}, keywords: {limit:3}, relations: {limit:3},  sentiment:{}})
    @result_hash = response.result
    
    @watson.update(
      text: @sun_text,
      sentiment_label: @result_hash["sentiment"]['document']['label'],
      sentiment_score: @result_hash["sentiment"]['document']['score'],
      emotion_sadness: @result_hash['emotion']['document']['emotion']['sadness'],
      emotion_joy: @result_hash['emotion']['document']['emotion']['joy'],
      emotion_fear: @result_hash['emotion']['document']['emotion']['fear'],
      emotion_disgust: @result_hash['emotion']['document']['emotion']['disgust'],
      emotion_anger: @result_hash['emotion']['document']['emotion']['anger'],
      keywords: @result_hash['keywords'],
      categories: @result_hash['categories']
    )
    redirect_to watson_path(@watson)
  end

  def show
    @watson = Watson.find(params[:id])
  end

  def destroy
    watson = Watson.find(params[:id])
    watson.destroy
    redirect_to watsons_path
  end

  private

  def strong_params
    params.require(:watson).permit(:text, :sentiment_label, :sentiment_score, :emotion_sadness, :emotion_joy, :emotion_fear, :emotion_disgust, :emotion_anger, :keywords, :categories)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/disclaimers/disclaimer.html.erb
<style>
body {
  background: url(<%= asset_path 'shodanbackground.jpg' %>);
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}
</style>

<h2 style="color:Lime ">To whom it may concern: the following is a collection of slides are questions gleaned from various old psych tests, movies, and the odd imagination of one half of this coding pair (I’m pretty sure you can guess who). Please don’t use this as a replacement for a real head shrinker or anything of the like. Please, however, understand IBM watson really is reading our lips through this glass door/computer monitor/projection screen. You have been warned.</h2>

<%= link_to "continue?", watsons_path %>

app/views/disclaimers/start.html.erb
<%= image_tag "disclaimer2.jpg" %>

<h5>(original picture by Jack Ziegler)</h5>
<h1>
Thank you for your patience. Please sit down and relax. The following 
questions will let us get a baseline for your emotions. Please answer in complete sentences to the best of your ability. Remember: there are no right or wrong answers, but for us to interpret your response you must answer with at least a full sentence.  We will start whenever you are ready.
</h1>

<%= link_to "continue?", new_watsons_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elementary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #0000CD " class="text-white" font-family="IBM Plex Mono", monospace;>
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
    <% if user_signed_in? %>
      <%= link_to "My Watsons", watsons_path, :class => "btn btn-light" %>
      <%=link_to "Analyze Text", new_watson_path, :class => "btn btn-primary" %>
      <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link btn btn-light' %> 
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link btn btn-light'  %>
    <% end %>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/slides/index.html.erb
<h1>WILL IT BLEND?</h1>

<% @slides.each do |slide| %>
    <%= link_to slide.keyword, slide_path(slide) %>
    <br>
    <hr>
<% end %>

app/views/slides/show.html.erb
<h1><%= @slide.prompt %></h1>
<br>
<%= image_tag @slide.photo %>

app/views/watsons/edit.html.erb
<br>
<br>
<div class="row">
  <div class="col-md-6">
<h6>Watson says: </h6>
<h6>Please write your answer in full sentences. I know you are capable.</h6>
<br>
<%= form_for @watson do |f| %>
  <%= f.text_area :text, :cols => "62", :rows => "10" %><br/><br>
  <%= f.submit "Re-Analyze", :class => "btn btn-success"%>
<% end %>
  </div>
</div>

app/views/watsons/index.html.erb
<% if user_signed_in? %>
    <% @array = @userwatsons.each do |userwatson| %>
        <% if userwatson.user_id == current_user.id %>
            <% userwatson.watson.text.truncate(1) %>
        <% end %>
    <% end.size %>
    
    <% if @array.size < 1 %>
        You have no submitted passages.
    <% else %>
    <br>
    <br>
    <div class="card">
  <div class="card-body">
        <table class="table table-striped table-dark" >
  <thead>
    <tr>
      <th scope="col" colspan="1">Watsons (Analyzed Texts)</th>
      <th scope="col">Sentiment</th>
      <th scope="col">Score</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <br>
    <% @userwatsons.each do |userwatson| %>
        <% if userwatson.user_id == current_user.id %>
            <tr>
                <th scope="row"><%= link_to userwatson.watson.text.truncate(100, separator: ' ', omission: '... (continued)'), watson_path(userwatson.watson), {:style=>'color:#FFFFFF;', :class => "css_class"} %></th>
                <td><%= userwatson.watson.sentiment_label.capitalize %></td>
                <td><%= number_to_percentage(userwatson.watson.sentiment_score * 100, precision: 1) %></td>
                <td>
                    <%= link_to 'Edit', edit_watson_path(userwatson.watson), :method => :get, :class => "btn btn-secondary" %> 
                    <%= link_to "Delete", delete_watson_path(userwatson.watson), method: :delete, :class => "btn btn-danger"  %>
                </td>
            </tr>
        <% end %>
    <% end %>
  </tbody>
</table>
  </div>
</div>
    <% end %>
<% end %>

app/views/watsons/new.html.erb
<br>
<div class="row">
  <div class="col-md-6">
    <%= image_tag @slide.photo, class: 'img' %>
  </div>
  <div class="col-md-6">
    <h6>Image prompt:</h6>
    <h3><%=  @slide.prompt%></h3>
    <hr>
<h6>Watson says: </h6>
<h6>Please write your answer in full sentences. I know you are capable.</h6>
<br>
<%= form_for @watson do |f| %>
  <%= f.text_area :text, :cols => "62", :rows => "10" %><br/><br>
  <%= f.submit "Analyze Me ;)", :class => "btn btn-success"%>
<% end %>
  </div>
</div>

app/views/watsons/show.html.erb
<br>
<% if current_user.id == @watson.users.first.id %>
<p style="text-align:right"><%= link_to 'Re-Analyze', edit_watson_path(@watson), :method => :get, :class => "btn btn-light" %> 
        <%= link_to "Delete", delete_watson_path(@watson), method: :delete, :class => "btn btn-danger"  %></p>
<h3>Watson received:</h3>
<div class="container"><center><%= @watson.text %></center></div><hr><br>
<h3>Watson says:</h3>
<div class="container"><center>
Your text is <font color="limegreen"><%= number_to_percentage(@watson.sentiment_score * 100, precision: 1) + " " + @watson.sentiment_label %></font> according to my supercomputing standards. See my parsed information below:
</center></div>
<br><br>
<div class="row">
        <div class="col-md-4">
        Emotion Analysis:
<br><br>
Joy: <%= number_to_percentage(@watson.emotion_joy.round(3) * 100, precision: 1) %><br>
Sadness: <%= number_to_percentage(@watson.emotion_sadness.round(3) * 100, precision: 1) %><br>
Fear: <%= number_to_percentage(@watson.emotion_fear.round(3) * 100, precision: 1) %><br>
Disgust: <%= number_to_percentage(@watson.emotion_disgust.round(3) * 100, precision: 1) %><br>
Anger: <%= number_to_percentage(@watson.emotion_anger.round(3) * 100, precision: 1) %><br>
        </div>
        <div class="col-md-4">
        Keywords:
<br>
<br>
<% @watson.keywords.each do |keyword| %>
    Text: <%= keyword.text.capitalize %><br>
    Relevance: <%= number_to_percentage(keyword.relevance * 100, precision: 1) %><br><br>
    <% end %>
        </div>
        <div class="col-md-4">
        Categories:
<br>
<br>
<% @watson.categories.each do |category| %> 
    <%= category.label.capitalize %><br><br>
<% end %>
        </div>
</div>
<% else %>
Sorry!
<% end %>